server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loans?useSSL=false&serverTimezone=UTC
    username: root
    password: Akki143@
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: "loans"

  profiles:
    active: "prod"

  config:
    import: "configserver:http://localhost:8071/"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"